// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgdvyfvcdivwzjxgrggv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nZHZ5ZnZjZGl2d3pqeGdyZ2d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNzA4MTksImV4cCI6MjA2ODc0NjgxOX0.IsqZo2HO__NTMyRaMSRba4BTwbgTV9i3FHCvtBOs9yY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});